version: '2'
services:
    mysql:
      image: mysql:8.0.20
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_USER=mysql
        - MYSQL_PASSWORD=mysql
      ports:
        - '3306:3306'
