version: '2'
services:
    postgres:
      image: postgres:13-alpine
      restart: always
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
      ports:
        - '5432:5432'
